name: Linux

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - 'wip/**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: koalaman/shellcheck-alpine:stable
    defaults:
      run:
        working-directory: .
    steps:
      - name: Clone dotfiles
        uses: actions/checkout@v3
      - name: ShellCheck
        run: |
          find . -type f -name '*.sh' | xargs shellcheck --external-sources --severity=error
          find . -type f -name '*.sh' | xargs shellcheck --external-sources --severity=style || echo "Shellcheck has some warnings"
